# Generated by Django 4.1.13 on 2024-04-18 04:32

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('client_url', models.CharField(max_length=500)),
                ('mapped_url', models.CharField(max_length=500)),
            ],
        ),
    ]
