# Generated by Django 4.1.13 on 2024-04-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='mapped_url',
            new_name='mapped_key',
        ),
    ]
